### ISSUE TITLE
サイファ公式からデータをスクレイピングする

### ISSUE THREAD

**Issue by KoheiB** [KoheiB/cipher_application#1]
ファイル形式はお任せします。
Firestoreにインポートしやすい形式でお願いします。
どうやるのか見てみたいから何らかの手段でコード共有してほしいです。

**Comment by henry1123k** [comment]
取り急ぎデータのスクレイピングできました。

リポジトリにetcフォルダ作って、そこにデータとコード突っ込もうと思うんですがいいですかね？

残ToDo
・スキルテキスト、支援スキルテキストの一部が消えてるので、どうするか検討。
　（常時スキルの「常」とか、3リバの表記とかがWebページ上だと画像になってるが、この部分を文字列形式に変換するロジックを入れてない。）

**Comment by KoheiB** [comment]
> リポジトリにetcフォルダ作って、そこにデータとコード突っ込もうと思うんですがいいですかね？

OKです！
Firestoreに突っ込む時に都合の良いようにしていただければいいと思います。

> ・スキルテキスト、支援スキルテキストの一部が消えてるので、どうするか検討。

その辺りのテキストを使うことって多分ないので、ひとまずは後回しでもいいと思います。（というかやらなくてもいい。）
Firestoreに突っ込むタスクの方が優先度高いですね。
