### ISSUE TITLE
カード名の「＋」表記が統一されていない問題について

### ISSUE THREAD

**Issue by henry1123k** [KoheiB/cipher_application#26]
タイトルの通り。
コード内でファイルパスやドキュメントパスを紐付ける際に不都合な状態である。
どうするかを検討する。

**Comment by KoheiB** [comment]
@henry11239987 
<img width="496" alt="スクリーンショット 2021-01-23 13 12 58" src="https://user-images.githubusercontent.com/60537225/105568466-d96c1880-5d7c-11eb-8152-da183572bcf3.png">
現状上のような感じでカードを表示しています。
当初は称号と名前、画像を表示させれば十分かと思っていましたが、IDがないと画像でしかプラスのカードを判断できないため、IDも表示させるようにしています。
そのため、firestoreの_idフィールドは今のままがいいなと思います。

imgUrlフィールドにフォルダパス(収録弾/カードID.png)を持たせてstatics/img + フォルダパスとかで表示するのが良いと思いますどうでしょうか？

**Comment by henry1123k** [comment]
### 現状
下記の通り、「＋」の表記ゆれが存在している。

- カード画像のファイル名は「plus」
- cloud firestoreのIDは「＋」

### 原因
サイファ公式ページでは下記の通り使い分けがされており、これをそのまま取ってきたため

- カード画像のファイル名は「plus」
- Webページ上に記載するカードIDでは「＋」

### 解決策１
「plus」表記に統一する

#### 懸念点
本アプリの画面上では「＋」表記にしたいため、cloud firestoreの表記が「plus」となった場合にそのまま使えなくなる。（一度置換するロジックを入れる必要がある。）

### 解決策２
「＋」表記に統一する

#### 懸念点
カード画像のファイル名に「＋」を使うことによる不具合が何かあるかもしれない（文字コードがどうたらみたいな）
サイファ公式が、意図的に「plus」表記にしていた点も引っかかる。

### 解決策３
表記は統一しない。
プログラム上で必要に応じて文字列を置換する。

#### 懸念点
「＋」と「plus」の文字列がレアリティ周り以外で出てきた場合、置換したくない箇所まで置換してしまう恐れあり。ただ、カードIDや画像ファイル名に関して言えば、レアリティ以外で「plus」と「＋」が出てくることはない認識。

**Comment by henry1123k** [comment]
解決策１はまあなくて、２か３だろうなという気持ちです。

２はそれなりに面倒なので、可能なら３がいいなあと思ってるのですがどうでしょうか。ファイルパス作成するタイミングで「.replace('+', 'plus')」ってつけるだけという認識です。

**Comment by KoheiB** [comment]
replaceで試したらできました！
これでいきましょう！
ありがとうございました

<img width="968" alt="スクリーンショット 2021-01-23 14 37 32" src="https://user-images.githubusercontent.com/60537225/105569834-8d26d580-5d88-11eb-929f-9cf1ac760811.png">
