### ISSUE TITLE
Cardsのsymbol1,symbol2について

### ISSUE THREAD

**Issue by KoheiB** [KoheiB/cipher_application#27]
CardsをシンボルでfilterをかけてFirestoreから読み込むのがFirestoreのクエリの都合上、余分なコストがかかってしまいそう。

例えば聖痕でFilterをかけてstore上からgetする場合、
symbol1またはsymbol2が聖痕のカードをクエリする手段がFirestoreにはありません。
（おそらくないです。もし現在の仕様のままクエリする方法があれば教えてください。）

作業中ブランチ：#23-searchCardList

この問題について２通りのアプローチを考えました。

１、セレクトに赤青、白黒の項目を追加して、直接クエリする。
デメリット：赤、青単体でフィルターしても赤青が出てこない。

２、symbolフィールドを新たに追加し、配列でシンボルを持たせ、array-containsクエリで指定する。
例：[白夜、暗夜]、[神器]、[（なし）]
デメリット：storeに新たにフィールドを追加するのが面倒そう

僕の中では２が有力です。調査の上、改善をお願いします！
方針が定まったら相談してください。

**Comment by henry1123k** [comment]
２の方針で、cloud firestoreに「Cards_new」というドキュメント追加しました。
こっち参照して問題解決するかの確認お願いします。
