### ISSUE TITLE
ユニット名の配列

### ISSUE THREAD

**Issue by KoheiB** [KoheiB/cipher_application#28]
autocompleteの中身として、ユニット名の配列が必要です。
- あいうえお順
- 重複なし

例
`unitNames: ['マルス', 'シーダ', 'ジェイガン'],`

↑はあいうえお順になってないけどユニット名リストから選択してフィルターかけられるようにします。

お願いします！

**Comment by henry1123k** [comment]
確認と提案です。

### 確認
下記で認識あっていますか？

検索ボックスを使ってユニット名で検索する際、オートコンプリート機能をつけたい。
これに当たり、ユニット名の一覧を配列形式で保持しておきたい。
この配列形式のデータをソースとして、オートコンプリート機能を実装する。

### 提案
cloud firestoreにもたせておくのか、アプリ内の定数置き場に置いておくのかは検討の余地があると思います。

個人的には後者推しです。
cloud firestoreのコレクションとして持つほどのものとはいまいち思えないのと、定数のほうが通信が不要になるという意味で高速ナノではないかと思います。

**Comment by KoheiB** [comment]
> 検索ボックスを使ってユニット名で検索する際、オートコンプリート機能をつけたい。
これに当たり、ユニット名の一覧を配列形式で保持しておきたい。
この配列形式のデータをソースとして、オートコンプリート機能を実装する。

合ってます！


> cloud firestoreにもたせておくのか、アプリ内の定数置き場に置いておくのかは検討の余地があると思います。

すみません、コレクションに入れるつもりではなかったです！
VSCode上で入力できれば十分です。

**Comment by henry1123k** [comment]
了解です。
issueのラベルがdataebaseになっていたので勘違いしました……
定数として用意しますね
