### ISSUE TITLE
カード検索画面　ユニット名フィルター機能改善

### ISSUE THREAD

**Issue by KoheiB** [KoheiB/cipher_application#32]
### 現在の仕様
ユニット名をカタカナまたは漢字でフィルターできる。
例）マルスを検索するには「マ」と打つ必要がある。

### 目指す仕様
カタカナ、漢字だけでなく、ひらがなで入れた時点でも読み仮名でフィルターできる。
例）マルスを検索するには「ま」と打てば良い。

### 調査結果
カスタムフィルターメソッドを作成してv-autocompleteのfilterAPIを使用する。
オブジェクト形式でItemsを用意する必要あり。

```
unitNameFilterItems: [
        { prop1: 'マルス', prop2: 'まるす' },
        { prop1: 'リン', prop2: 'りん' },
        { prop1: '門番', prop2: 'もんばん' },
        { prop1: '？？？', prop2: 'はてな' },
　　・・・
]
```

上記のようなオブジェクト型での作成をお願いしたいです。
最初からこっちの形式で頼めてれば良かったんですが、今日思いついて調査したので・・・すみません。
現状の仕様でも使用には事足りますので、Issueの優先度は低めです。

また、これに伴って、以下について相談したいです。

- prop1,prop2の命名
- 漢字のユニット名の順番
漢字勢はフィルターの最後の方にまとめて読み仮名でソートするか、カタカナのユニットと混ぜて読み仮名でソートするか。（マジ、魔女、マチス・・・みたいにするか）

**Comment by henry1123k** [comment]
対応しました。プルリク確認お願いします。

相談事項についてどうしたか、回答します。

- prop1,prop2の命名
→name,hiraganaにしましたがどうでしょう。「hiragana」は気持ち悪いですが、英語では存在しない概念なので泣く泣く。。。という経緯です。

- 漢字のユニット名の順番
   漢字勢はフィルターの最後の方にまとめて読み仮名でソートするか、カタカナのユニットと混ぜて読み仮名でソートするか。（マジ、魔女、マチス・・・みたいにするか）
→カタカナのユニットと混ぜました。ユーザビリティ考えるとこのほうが良いという判断です。
（蒼井 樹　を探すとき、当然「あ」から打ち始めるわけで、その際に引っかかってくれたほうが個人的には嬉しい、というイメージ）
